SELECT
    ORDER_ID,
    SHOPPER_ID,
    AGE,
    MONTH_YEAR_ORDER,
    PRODUCT,
    MERCHANT,
    DEFAULT_TYPE,
    DELAY_PERIOD
    SUM(LOANS_IN_ARREARS_DEBT) / SUM(TOTAL_LOAN_AMOUNT) AS DEFAULT_RATIO
FROM {{ref('output_dataset')}}
;

